coverage:
  path: ./coverage
  status:
    patch:
      default:
        target: 100% # Makes sure all new code is tested
        informational: true # Don't fail the build if coverage is below target
  status:
    project:
      default:
        threshold: 0.1
    patch: off
  
comment: false
